Pendle agent
gizatechxyz/Giza-zkml-Hub pull request #21
Opened 2024-05-07 14:41 UTC by EgeAtesalp

Pendle Agent Implementation + Tutorial

2024-05-08 11:38 UTC, jwarmuz99 commented on awesome-giza-agents/Pendle-Agent/agent/addresses.py
> +    "wallet_address" : "0xB2187A3Fd675Cc4243AD37b2dEdE3e145BAD27FC",
remove

2024-05-08 11:50 UTC, jwarmuz99 requested changes
Great stuff! 

I left some minor comments. Also, following feedback I received from Gonzalo: 
- We should execute `black`, `isort` and `ruff` in the python scripts to improve linting and formatting. 
- I think that we should add at least a requirements.txt with the dependencies so is easily reproducible

2024-05-08 11:50 UTC, jwarmuz99 commented on awesome-giza-agents/Pendle-Agent/agent/addresses.py
> +    "wallet_address" : "0xB2187A3Fd675Cc4243AD37b2dEdE3e145BAD27FC",
remove the wallet address from here

2024-05-08 11:50 UTC, jwarmuz99 commented on awesome-giza-agents/Pendle-Agent/agent/agent.py
> +    wallet_address = ADDRESSES["wallet_address"]
The way you’re using wallet_address, I would remove it from addresses.py and rather than reading from the file, i would just use the agent’s wallet address. you can make it optional and let ppl provide it with defaulting to agent wallet addy

2024-05-08 11:50 UTC, jwarmuz99 commented on awesome-giza-agents/Pendle-Agent/agent/agent.py
> +    chain=f"ethereum:mainnet_fork:foundry",
typo. should be: `chain=f"ethereum:mainnet-fork:foundry",`

2024-05-08 11:50 UTC, jwarmuz99 commented on awesome-giza-agents/Pendle-Agent/agent/setup.py
> +network = "ethereum:mainnet_fork:foundry"  ## We ask the Ape Framework to locate our forked mainnet
typo. should be: `chain=f"ethereum:mainnet-fork:foundry",`

2024-05-08 11:50 UTC, jwarmuz99 commented on awesome-giza-agents/Pendle-Agent/model/yield_prediction_model.ipynb
love how well explained with all the screenshots this is

2024-05-08 11:57 UTC, EgeAtesalp commented on awesome-giza-agents/Pendle-Agent/agent/agent.py
> +    wallet_address = ADDRESSES["wallet_address"]
Hey Jakub, do you know how to access wallet address? agent.address doesn't work (the way it would work with a normal ape wallet.

2024-05-08 12:15 UTC, alejandromartinezgotor commented on awesome-giza-agents/Pendle-Agent/agent/agent.py
> +
Run a code formatter like black to avoid these blanks and some other small things.

2024-05-08 12:27 UTC, alejandromartinezgotor commented on awesome-giza-agents/Pendle-Agent/data/weETH_daily_yield.parquet
this data is not in our datasets? Have you prepared them locally and uploaded them?

2024-05-08 12:30 UTC, EgeAtesalp commented on awesome-giza-agents/Pendle-Agent/data/weETH_daily_yield.parquet
Currently yes, I am creating datasets for all popular wrapped -LP tokens now, will change this once I have them in giza-datasets

2024-05-08 12:30 UTC, EgeAtesalp commented
Formatting + linting done!

2024-05-10 09:11 UTC, jwarmuz99 commented on awesome-giza-agents/Pendle-Agent/agent/agent.py
> +    wallet_address = ADDRESSES["wallet_address"]
In the SY_PY_swap action, you are providing the account alias as an argument. You can use this to load the account and fetch its address. Sth like the following should work:

```
from ape import accounts
agent_address = accounts.load(account).address
```

2024-05-10 10:48 UTC, EgeAtesalp commented on awesome-giza-agents/Pendle-Agent/agent/agent.py
> +    wallet_address = ADDRESSES["wallet_address"]
Thank you!

2024-05-10 12:33 UTC, jwarmuz99 approved these changes

2024-05-10 13:13 UTC, merged